pretrained_model_path: /workspace/stable-diffusion-v1-5
logdir: ./stage1_log/
train_steps: 15000
validation_steps: 500
validation_sample_logger:
  num_inference_steps: 40
  guidance_scale: 7
gradient_accumulation_steps: 10
seed: 6666
mixed_precision: fp16
train_batch_size: 12
val_batch_size: 1
learning_rate: 1.0e-05
scale_lr: false
lr_scheduler: constant
lr_warmup_steps: 0
use_8bit_adam: true
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
checkpointing_steps: 5000
